import{a as d,S as f,i as c}from"./assets/vendor-DQq26VV5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function a(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(r){if(r.ep)return;r.ep=!0;const n=a(r);fetch(r.href,n)}})();function y(t){return d.get("https://pixabay.com/api/",{params:{key:"53361470-387588d6f5d48c87f9e06e518",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(e=>e.data.hits).catch(e=>{console.error(e)})}let i;function m(t){let e=document.querySelector(".gallery");e===null&&(document.querySelector(".container").insertAdjacentHTML("afterend",'<ul class="gallery"></ul>'),e=document.querySelector(".gallery"));const a=t.map(o=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${o.largeImageURL}">
                <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
            </a>
            <div class="info">
                <p class="gallery-info-item">Likes <span>${o.likes}</span></p>
                <p class="gallery-info-item">Views <span>${o.views}</span></p>
                <p class="gallery-info-item">Comments <span>${o.comments}</span></p>
                <p class="gallery-info-item">Downloads <span>${o.downloads}</span></p>
            </div>
        </li>`).join("");i===void 0&&(i=new f(".gallery a",{captionsData:"alt",captionDelay:250})),e.insertAdjacentHTML("beforeend",a),i.refresh()}function p(){const t=document.querySelector(".gallery");t.innerHTML=""}function g(){let t=document.querySelector(".loader");t===null&&(document.querySelector(".container").insertAdjacentHTML("beforeend",'<span class="loader visually-hidden"></span>'),t=document.querySelector(".loader")),t.classList.remove("visually-hidden")}function h(){document.querySelector(".loader").classList.add("visually-hidden")}const s=document.querySelector(".form"),u=document.querySelector(".form-input");s.addEventListener("submit",t=>{if(t.preventDefault(),u.value.trim()===""){c.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),s.reset();return}p(),g(),y(u.value).then(e=>{!e||e.length===0?c.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):m(e)}).catch(e=>{console.error("Error fetching images:",e)}).finally(()=>{h()}),s.reset()});
//# sourceMappingURL=index.js.map
