import{a as d,S as f,i as c}from"./assets/vendor-DQq26VV5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();function y(r){return d.get("https://pixabay.com/api/",{params:{key:"53361470-387588d6f5d48c87f9e06e518",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(e=>e.data.hits).catch(e=>{console.error(e)})}let i;function m(r){const e=document.querySelector(".gallery");e===null&&(document.querySelector(".container").insertAdjacentHTML("afterend",'<ul class="gallery"></ul>'),e=document.querySelector(".gallery"));const a=r.map(n=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${n.largeImageURL}">
                <img class="gallery-image" src="${n.webformatURL}" alt="${n.tags}" loading="lazy" />
            </a>
            <div class="info">
                <p class="gallery-info-item">Likes <span>${n.likes}</span></p>
                <p class="gallery-info-item">Views <span>${n.views}</span></p>
                <p class="gallery-info-item">Comments <span>${n.comments}</span></p>
                <p class="gallery-info-item">Downloads <span>${n.downloads}</span></p>
            </div>
        </li>`).join("");i===void 0&&(i=new f(".gallery a",{captionsData:"alt",captionDelay:250})),i.refresh(),e.insertAdjacentHTML("beforeend",a)}function p(){const r=document.querySelector(".gallery");r.innerHTML=""}function g(){const r=document.querySelector(".loader");r===null&&(document.querySelector(".container").insertAdjacentHTML("afterend",'<span class="loader visually-hidden"></span>'),r=document.querySelector(".loader")),r.classList.remove("visually-hidden")}function h(){document.querySelector(".loader").classList.add("visually-hidden")}const s=document.querySelector(".form"),u=document.querySelector(".form-input");s.addEventListener("submit",r=>{if(r.preventDefault(),u.value.trim()===""){c.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),s.reset();return}p(),g(),y(u.value).then(e=>{!e||e.length===0?c.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):m(e)}).catch(e=>{console.error("Error fetching images:",e)}).finally(()=>{h()}),s.reset()});
//# sourceMappingURL=index.js.map
